version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coviddata"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ylnsnffh39kw"
s3_prefix = "coviddata"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

